fixes:
  - "pennylane_qchem/::qchem/pennylane_qchem/"

ignore:
  - "pennylane/devices/tests/*"
  - "home/runner/work/pennylane/pennylane/pennylane/::pennylane/" 

codecov:
  notify:
    after_n_builds: 6

comment:
  after_n_builds: 6
